#!/bin/bash

# compile_wrf.sh
# Compile WRF from local files and handle decompression of required files.

# Define paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"  # Directory where the script is located
# Source common helpers (colors)
if [ -f "$SCRIPT_DIR/common.sh" ]; then
  # shellcheck source=/dev/null
  source "$SCRIPT_DIR/common.sh"
fi
# If an env file was generated by the installer, source it so variables are consistent
ENV_FILE_DEFAULT="$HOME/models/wrf/wrf_env.sh"
if [ -f "${ENV_FILE:-$ENV_FILE_DEFAULT}" ]; then
  # shellcheck source=/dev/null
  source "${ENV_FILE:-$ENV_FILE_DEFAULT}"
fi
# Allow overriding installation base directory via env var.
# Default: place installs under the user's home as requested by user.
WRF_CHEM_FILES_DIR="$SCRIPT_DIR/WRF_CHEM_FILES"  # Directory containing WRF-Chem files

# Determine whether we're building WRF or WRF-Chem.
# Priority: COMPILE_TARGET env var ("wrf" or "wrf-chem"); else prompt interactively if terminal, otherwise detect presence of WRF_CHEM_FILES.
if [ -n "${COMPILE_TARGET:-}" ]; then
  case "${COMPILE_TARGET,,}" in
    wrf|wrf-chem|wrf_chem)
      if [[ "${COMPILE_TARGET,,}" == "wrf" ]]; then
        WRF_CHEM=0
      else
        WRF_CHEM=1
      fi
      ;;
    *)
      info "Unrecognized COMPILE_TARGET='${COMPILE_TARGET}'; falling back to auto-detect."
      unset COMPILE_TARGET
      ;;
  esac
fi

if [ -z "${COMPILE_TARGET:-}" ]; then
  # If running interactively on a tty, ask the user which target to build.
  if [ -t 0 ]; then
    # Determine a sensible default based on presence of WRF_CHEM_FILES
    if [ -d "$WRF_CHEM_FILES_DIR" ] && [ -n "$(ls -A "$WRF_CHEM_FILES_DIR" 2>/dev/null || true)" ]; then
      default_choice=2
    else
      default_choice=1
    fi

    echo
    echo "Which target would you like to build?"
    echo "  1) WRF (no chemistry)"
    echo "  2) WRF-Chem (with atmospheric chemistry)"
    echo ""
    read -r -p "Enter choice [1-2] (default ${default_choice}): " choice
    choice=${choice:-$default_choice}
    case "$choice" in
      1) WRF_CHEM=0; COMPILE_TARGET=wrf ;;
      2) WRF_CHEM=1; COMPILE_TARGET=wrf-chem ;;
      *)
        echo "Invalid choice '$choice' - defaulting to option ${default_choice}."
        if [ "$default_choice" -eq 2 ]; then WRF_CHEM=1; COMPILE_TARGET=wrf-chem; else WRF_CHEM=0; COMPILE_TARGET=wrf; fi
        ;;
    esac
    echo "Selected: ${COMPILE_TARGET}"
  else
    # Non-interactive: detect by presence of WRF_CHEM_FILES as before
    if [ -d "$WRF_CHEM_FILES_DIR" ] && [ -n "$(ls -A "$WRF_CHEM_FILES_DIR" 2>/dev/null || true)" ]; then
      WRF_CHEM=1
      COMPILE_TARGET=wrf-chem
    else
      WRF_CHEM=0
      COMPILE_TARGET=wrf
    fi
  fi
fi

# Default INSTALL_BASE if not set externally
if [ -z "${INSTALL_BASE:-}" ]; then
  if [ "$WRF_CHEM" -eq 1 ]; then
    INSTALL_BASE="$HOME/models/wrf-chem"
  else
    INSTALL_BASE="$HOME/models/wrf"
  fi
else
  INSTALL_BASE="$INSTALL_BASE"
fi

info "Setting up WRF environment..."

# Ensure install directory exists
mkdir -p "$INSTALL_BASE"

if [ "$WRF_CHEM" -eq 1 ]; then
  info "Detected target: WRF-Chem; installing to $INSTALL_BASE"
else
  info "Detected target: WRF; installing to $INSTALL_BASE"
fi

# Decompress WRF.tar.gz and WPS.tar.gz into INSTALL_BASE
info "Decompressing WRF.tar.gz into ${INSTALL_BASE}..."
tar -xzf "$WRF_CHEM_FILES_DIR/WRF.tar.gz" -C "$INSTALL_BASE"
info "Decompressing WPS.tar.gz into ${INSTALL_BASE}..."
tar -xzf "$WRF_CHEM_FILES_DIR/WPS.tar.gz" -C "$INSTALL_BASE"

# Navigate to the decompressed WRFV3 directory
cd "$INSTALL_BASE/WRF" || { error "Failed to enter WRF directory."; exit 1; }

# Set environment variables for WRF
export WRF_EM_CORE=1
export WRF_NMM_CORE=0
export WRF_CHEM=$WRF_CHEM
export WRF_KPP=0

# Clean WRF
info "Cleaning WRF..."
./clean -a

# Attempt to auto-detect the best configure option by inspecting available compilers
detect_recommended_option() {
  info "Detecting compilers to recommend a configure option..."
  local prefer="gfortran"
  if command -v ifort >/dev/null 2>&1 || command -v ifx >/dev/null 2>&1; then
    prefer="ifort"
  elif command -v gfortran >/dev/null 2>&1; then
    prefer="gfortran"
  fi

  # Try to parse the configure script for matching lines
  local cfg_file="./configure"
  if [ ! -f "$cfg_file" ]; then
    echo "Warning: configure script not found for parsing. Falling back to default recommendation."
    echo "$prefer"
    return
  fi

  # Read first 500 lines of configure (menu usually near top) and search for lines containing keywords
  local menu_chunk
  menu_chunk=$(sed -n '1,500p' "$cfg_file" 2>/dev/null || true)

  # Try several patterns to extract the number associated with a matching option
  local number
  number=$(echo "$menu_chunk" | grep -nE '^[[:space:]]*[0-9]+[[:space:]]*\)' | sed -n '1,200p' | grep -i "$prefer" | head -n1 | sed -E 's/^[[:space:]]*([0-9]+).*/\1/')
  if [ -z "$number" ]; then
    number=$(echo "$menu_chunk" | grep -nE '^[[:space:]]*[0-9]+\.' | sed -n '1,200p' | grep -i "$prefer" | head -n1 | sed -E 's/^[[:space:]]*([0-9]+).*/\1/')
  fi
  if [ -z "$number" ]; then
    # Fallback: search any line containing the keyword and pick the first number found on that line
    number=$(echo "$menu_chunk" | grep -i "$prefer" | head -n1 | grep -oE '[0-9]+' | head -n1 || true)
  fi

  if [ -n "$number" ]; then
    echo "$number"
    return
  fi

  # Try a wider search: find any numbered option that mentions the preferred compiler
  number=$(echo "$menu_chunk" | grep -nE '^[[:space:]]*[0-9]+' | grep -i "$prefer" | sed -E 's/^[[:space:]]*([0-9]+).*/\1/' | head -n1 || true)
  if [ -n "$number" ]; then
    echo "$number"
    return
  fi

  # Fallback: pick the first numeric option in the menu (non-interactive default)
  number=$(echo "$menu_chunk" | grep -nE '^[[:space:]]*[0-9]+' | sed -n '1p' | sed -E 's/^[[:space:]]*([0-9]+).*/\1/' || true)
  if [ -n "$number" ]; then
    echo "$number"
    return
  fi

  # If nothing found, return empty string
  echo ""
}

info "Configuring WRF (attempting automatic selection)..."
# Allow user to force a configure menu selection via CONFIGURE_CHOICE env var
if [ -n "${CONFIGURE_CHOICE:-}" ]; then
  info "CONFIGURE_CHOICE is set: using $CONFIGURE_CHOICE as the configure selection."
  recommended="$CONFIGURE_CHOICE"
else
  recommended=$(detect_recommended_option)
fi

# run_configure_with_choice: try several non-interactive strategies to run ./configure
run_configure_with_choice() {
  local choice="$1"

  # Strategy 1: pipe the choice and two blank lines
  {
    printf "%s\n" "$choice"
    printf "\n"
    printf "\n"
  } | ./configure
  local rc=$?
  if [ $rc -eq 0 ]; then
    return 0
  fi

  # Strategy 2: use expect to interact with the pty if available
  if command -v expect >/dev/null 2>&1; then
    info "./configure ignored pipe; using expect to provide the selection ($choice)"
    expect <<EOF
spawn ./configure
set timeout -1
expect {
  -re "Enter selection" {
    send "$choice\r"
    send "\r"
    send "\r"
    exp_continue
  }
  -re "Enter selection \[[0-9]+-[0-9]+\]" {
    send "$choice\r"
    send "\r"
    send "\r"
    exp_continue
  }
  -re "Select" {
    send "$choice\r"
    send "\r"
    send "\r"
    exp_continue
  }
  -re "Choice" {
    send "$choice\r"
    send "\r"
    send "\r"
    exp_continue
  }
  eof
}
EOF
    return $?
  fi

  # Strategy 3: run under pseudo-tty using script and feed input
  if command -v script >/dev/null 2>&1; then
    info "Attempting to run ./configure under pseudo-tty (script) with choice: $choice"
    printf "%s\n\n" "$choice" | script -q /dev/null ./configure
    return $?
  fi

  return $rc
}

DEFAULT_CONFIGURE_CHOICE=35

if [[ "$recommended" =~ ^[0-9]+$ ]]; then
  info "Using configure option number: $recommended (automatically selected)."
  if ! run_configure_with_choice "$recommended"; then
    error "Error: WRF configuration failed (non-interactive configure). Try running ./configure interactively in $INSTALL_BASE/WRF."
    exit 1
  fi
else
  if [ -n "$recommended" ]; then
    info "Could not parse a menu number but detected preferred compiler string: $recommended"
    retry_num=$(detect_recommended_option)
    if [[ "$retry_num" =~ ^[0-9]+$ ]]; then
      info "Found numeric option on retry: $retry_num"
      if ! run_configure_with_choice "$retry_num"; then
        error "Configure failed with option $retry_num"; exit 1
      fi
    else
      info "No numeric option found. Defaulting to recommended choice $DEFAULT_CONFIGURE_CHOICE and trying non-interactively."
      recommended="$DEFAULT_CONFIGURE_CHOICE"
      if ! run_configure_with_choice "$recommended"; then
        error "Configure failed; interactive run may be required."; exit 1
      fi
    fi
  else
    info "Could not detect a preferred compiler or option; falling back to first menu option."
    recommended="$DEFAULT_CONFIGURE_CHOICE"
    info "Falling back to default choice $recommended and attempting configure."
    if ! run_configure_with_choice "$recommended"; then
      error "Configure failed; interactive run may be required."; exit 1
    fi
  fi
fi

# Compile WRF
info "Compiling WRF (this may take a while)..."
if [ -x "$INSTALL_BASE/WRF/main/wrf.exe" ] || [ -x "$INSTALL_BASE/WRF/main/wrf" ]; then
  success "WRF already appears compiled (wrf executable found). Skipping compilation."
else
  ./compile em_real > compile.log 2>&1 &

  # Monitor the compilation log
  info "Monitoring compilation log..."
  tail -f compile.log &
  TAIL_PID=$!

  # Wait for the compilation to finish
  wait $!

  # Kill tail when compile finishes
  kill $TAIL_PID 2>/dev/null || true

  # Check if compilation succeeded
  if grep -q "Executables successfully built" compile.log; then
    success "WRF compilation complete!"
  else
    error "Error: WRF compilation failed. Check compile.log for details."
    exit 1
  fi
fi