# WRF environment variables (generated by install_wrf_libraries.sh)
export DIR="/home/hector/Desktop/Projects/Install-WRF-Chem/LIBRARIES"
export CC=gcc
export CXX=g++
export FC=gfortran
export CFLAGS=-m64
export F77=gfortran
export FFLAGS=-m64
export PATH="/home/hector/Desktop/Projects/Install-WRF-Chem/LIBRARIES/netcdf/bin:$PATH"
export NETCDF="/home/hector/Desktop/Projects/Install-WRF-Chem/LIBRARIES/netcdf"
